export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_PRODUCT_IN_CART = 'UPDATE_PRODUCT_IN_CART';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const RESET_CART = 'RESET_CART';
export const SET_USER = 'SET_USER';
export const SET_MODAL_VISIBLE = 'SET_MODAL_VISIBLE';
